# Generated by Django 4.2.16 on 2024-11-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='book',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
